# coding=utf8
"""
HTTP 状态码及自定义返回信息
"""

OK = "OK"
ERR = "ERR"
ERR_BAD_PARAMS = "ERR_BAD_PARAMS"
ERR_SERVER_EXCEPTION = "ERR_SERVER_EXCEPTION"

HTTP_OK = 200
# 重定向
HTTP_REDIRECT = 302
# 参数错误
HTTP_BAD_PARAM = 400
# 未认证
HTTP_UNAUTHORIZED = 401
# 未授权
HTTP_FORBIDDEN = 403
HTTP_NOT_FOUND = 404
HTTP_PART_NOT_FOUND = 406
# 服务端异常
HTTP_SERVER_ERROR = 500
