
OK = "OK"
ERR = "ERR"
ERR_BAD_PARAMS = "ERR_BAD_PARAMS"
ERR_SERVER_EXCEPTION = "ERR_SERVER_EXCEPTION"

HTTP_OK = 200
HTTP_BAD_PARAM = 400
HTTP_NOT_FOUND = 404
HTTP_PART_NOT_FOUND = 406
HTTP_SERVER_ERROR = 500
